<?php

use Illuminate\Database\Seeder;

class CalendarsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('calendars')->delete();
        
        \DB::table('calendars')->insert(array (
            0 => 
            array (
                'id' => 1,
                'action_id' => 2,
            'year_2020' => 'L’infrastructure écologique est cartographiée et disponible dans le SITG (résolution : 25 mètres)',
                'year_2021' => 'Mise à jour selon l’évolution des projets et du territoire',
                'year_2022' => 'Mise à jour selon l’évolution des projets et du territoire',
                'year_2023' => 'Mise à jour selon l’évolution des projets et du territoire',
                'created_at' => '2020-04-10 16:05:49',
                'updated_at' => '2020-04-10 16:05:49',
            ),
            1 => 
            array (
                'id' => 2,
                'action_id' => 3,
                'year_2020' => 'Déploiement de la campagne dans les médias et sur les réseaux sociaux',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 16:08:45',
                'updated_at' => '2020-04-10 16:08:45',
            ),
            2 => 
            array (
                'id' => 3,
                'action_id' => 4,
            'year_2020' => 'L’infrastructure écologique est disponible dans le SITG au niveau parcellaire, pour l’ensemble du canton (résolution : 25 mètres). Assurer l’espace nécessaire à long terme et de manière contraignante sur le plan de l’aménagement du territoire Prendre des mesures visant à valoriser, maintenir et accroître la perméabilité',
            'year_2021' => 'L’infrastructure écologique est disponible dans le SITG au niveau parcellaire, pour l’ensemble du canton (résolution : 25 mètres). Assurer l’espace nécessaire à long terme et de manière contraignante sur le plan de l’aménagement du territoire Prendre des mesures visant à valoriser, maintenir et accroître la perméabilité',
            'year_2022' => 'L’infrastructure écologique est disponible dans le SITG au niveau parcellaire, pour l’ensemble du canton (résolution : 25 mètres). Assurer l’espace nécessaire à long terme et de manière contraignante sur le plan de l’aménagement du territoire Prendre des mesures visant à valoriser, maintenir et accroître la perméabilité',
                'year_2023' => 'Garantir les financements au-delà de 2024',
                'created_at' => '2020-04-10 16:10:58',
                'updated_at' => '2020-04-10 16:10:58',
            ),
            3 => 
            array (
                'id' => 4,
                'action_id' => 5,
                'year_2020' => 'Finalisation',
                'year_2021' => 'Actualisation',
                'year_2022' => 'Actualisation',
                'year_2023' => 'Actualisation',
                'created_at' => '2020-04-10 16:58:47',
                'updated_at' => '2020-04-10 16:58:47',
            ),
            4 => 
            array (
                'id' => 5,
                'action_id' => 6,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 17:02:20',
                'updated_at' => '2020-04-10 17:02:20',
            ),
            5 => 
            array (
                'id' => 6,
                'action_id' => 7,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 17:06:56',
                'updated_at' => '2020-04-10 17:06:56',
            ),
            6 => 
            array (
                'id' => 7,
                'action_id' => 8,
                'year_2020' => 'Élaboration de la méthodologie et recensement des sites d’intérêt.',
                'year_2021' => 'Définition du statut des sites identifiés et acquisition selon les opportunités.',
                'year_2022' => 'Ajout de nouveaux sites et acquisition selon les opportunités.',
                'year_2023' => 'Ajout de nouveaux sites et acquisition selon les opportunités.',
                'created_at' => '2020-04-10 17:09:21',
                'updated_at' => '2020-04-10 17:09:21',
            ),
            7 => 
            array (
                'id' => 8,
                'action_id' => 9,
            'year_2020' => 'Elaboration (nouvelles réserves naturelles), renouvellement (réserves naturelles existantes), mise en œuvre et amélioration continue des plans de gestion.',
            'year_2021' => 'Elaboration (nouvelles réserves naturelles), renouvellement (réserves naturelles existantes), mise en œuvre et amélioration continue des plans de gestion.',
            'year_2022' => 'Elaboration (nouvelles réserves naturelles), renouvellement (réserves naturelles existantes), mise en œuvre et amélioration continue des plans de gestion.',
            'year_2023' => 'Elaboration (nouvelles réserves naturelles), renouvellement (réserves naturelles existantes), mise en œuvre et amélioration continue des plans de gestion.',
                'created_at' => '2020-04-10 17:12:17',
                'updated_at' => '2020-04-10 17:12:17',
            ),
            8 => 
            array (
                'id' => 9,
                'action_id' => 10,
                'year_2020' => 'Sensibilisation, formation, implication et accompagnement',
                'year_2021' => 'Sensibilisation, formation, implication et accompagnement',
                'year_2022' => 'Sensibilisation, formation, implication et accompagnement',
                'year_2023' => 'Sensibilisation, formation, implication et accompagnement',
                'created_at' => '2020-04-10 17:15:30',
                'updated_at' => '2020-04-10 17:15:30',
            ),
            9 => 
            array (
                'id' => 10,
                'action_id' => 11,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 17:17:42',
                'updated_at' => '2020-04-10 17:17:42',
            ),
            10 => 
            array (
                'id' => 11,
                'action_id' => 12,
                'year_2020' => 'Â établir lors de la mise en œuvre de l’action',
                'year_2021' => 'Â établir lors de la mise en œuvre de l’action',
                'year_2022' => 'Â établir lors de la mise en œuvre de l’action',
                'year_2023' => 'Â établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 17:23:13',
                'updated_at' => '2020-04-10 17:23:13',
            ),
            11 => 
            array (
                'id' => 12,
                'action_id' => 19,
                'year_2020' => 'Intégration de l’objectif de préservation de la quantité de l’eau dans le plan d’actions CIPEL',
                'year_2021' => 'Intégration de l’objectif de préservation de la quantité de l’eau dans le plan d’actions CIPEL',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 17:45:57',
                'updated_at' => '2020-04-10 17:45:57',
            ),
            12 => 
            array (
                'id' => 13,
                'action_id' => 20,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 17:48:40',
                'updated_at' => '2020-04-10 17:48:40',
            ),
            13 => 
            array (
                'id' => 14,
                'action_id' => 23,
                'year_2020' => 'Adoption d’un plan de gestion de forêt le long d’un cours d’eau cantonal',
                'year_2021' => 'Adoption d’un plan de gestion de forêt le long d’un cours d’eau cantonal',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'Adoption d’un plan de gestion de forêt le long d’un cours d’eau cantonal',
                'created_at' => '2020-04-10 18:00:05',
                'updated_at' => '2020-04-10 18:00:05',
            ),
            14 => 
            array (
                'id' => 15,
                'action_id' => 23,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'Début de l’élaboration du plan de gestion de forêt le long d’un cours d’eau communal',
                'year_2022' => 'Adoption du plan de gestion de forêt le long d’un cours d’eau communal',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:00:05',
                'updated_at' => '2020-04-10 18:00:05',
            ),
            15 => 
            array (
                'id' => 16,
                'action_id' => 24,
                'year_2020' => 'Elaboration de la planification des infrastructures liées à la navigation',
                'year_2021' => 'Elaboration de la planification des infrastructures liées à la navigation',
                'year_2022' => 'Elaboration de la planification des infrastructures liées à la navigation',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:04:06',
                'updated_at' => '2020-04-10 18:04:06',
            ),
            16 => 
            array (
                'id' => 17,
                'action_id' => 24,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'Elaboration de la directive concernant les matériaux en contact avec le Lac et les cours d’eau',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:04:06',
                'updated_at' => '2020-04-10 18:04:06',
            ),
            17 => 
            array (
                'id' => 18,
                'action_id' => 25,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:10:48',
                'updated_at' => '2020-04-10 18:10:48',
            ),
            18 => 
            array (
                'id' => 19,
                'action_id' => 27,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:18:19',
                'updated_at' => '2020-04-10 18:18:19',
            ),
            19 => 
            array (
                'id' => 20,
                'action_id' => 28,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:31:22',
                'updated_at' => '2020-04-10 18:31:22',
            ),
            20 => 
            array (
                'id' => 21,
                'action_id' => 29,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:33:34',
                'updated_at' => '2020-04-10 18:33:34',
            ),
            21 => 
            array (
                'id' => 22,
                'action_id' => 30,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:36:00',
                'updated_at' => '2020-04-10 18:36:00',
            ),
            22 => 
            array (
                'id' => 23,
                'action_id' => 31,
                'year_2020' => 'Réalisation de la roselière centrale',
                'year_2021' => 'Réalisation de la roselière Ouest',
                'year_2022' => 'À établir lors de la mise en œuvre de l’action',
                'year_2023' => 'Réalisation de la roselière Est',
                'created_at' => '2020-04-10 18:38:57',
                'updated_at' => '2020-04-10 18:38:57',
            ),
            23 => 
            array (
                'id' => 24,
                'action_id' => 32,
                'year_2020' => 'Communication à un large public et utilisation des résultats pour améliorer la mise en œuvre de la politique agricole et procéder cas échéant, aux adaptations réglementaires qui s’imposent',
                'year_2021' => 'Utilisation des résultats pour améliorer la mise en œuvre de la politique agricole en matière de promotion de la biodiversité',
                'year_2022' => 'Utilisation des résultats pour améliorer la mise en œuvre de la politique agricole en matière de promotion de la biodiversité',
                'year_2023' => 'Utilisation des résultats pour améliorer la mise en œuvre de la politique agricole, notamment dans le cadre de RAE',
                'created_at' => '2020-04-10 18:44:58',
                'updated_at' => '2020-04-10 18:44:58',
            ),
            24 => 
            array (
                'id' => 25,
                'action_id' => 33,
                'year_2020' => 'Finalisation de l’étude bibliographique, établissement du protocole de recherche basé sur des études similaires déjà réalisées Constitution des équipes de recherche et d’un groupe de projet Début des campagnes sur le terrain',
                'year_2021' => 'Campagnes de terrain et ajustement du protocole avec les exploitants Discussion des résultats et rédaction des premiers rapports provisoires',
                'year_2022' => 'Campagnes de terrain et ajustement du protocole avec les exploitants Discussions sur la mise en œuvre des recommandations, finalisation des rapports',
                'year_2023' => 'Proposition des premières mesures concrètes pour les agriculteurs.',
                'created_at' => '2020-04-10 18:48:01',
                'updated_at' => '2020-04-10 18:48:01',
            ),
            25 => 
            array (
                'id' => 26,
                'action_id' => 34,
                'year_2020' => 'À établir lors de la mise en œuvre de l’action',
                'year_2021' => 'À établir lors de la mise en œuvre de l’action',
                'year_2022' => 'Fédérer un groupe d’expert et organiser des séances de coordination',
                'year_2023' => 'Choix et validation de la méthode',
                'created_at' => '2020-04-10 18:51:12',
                'updated_at' => '2020-04-10 18:51:12',
            ),
            26 => 
            array (
                'id' => 27,
                'action_id' => 35,
                'year_2020' => 'Amélioration continue des mélanges grainiers Continuer la mise en œuvre des essais',
                'year_2021' => 'Amélioration continue des mélanges grainiers Continuer la mise en œuvre des essais',
                'year_2022' => 'Amélioration continue des mélanges grainiers Continuer la mise en œuvre des essais Communiquer à plus large échelles les premiers résultats',
                'year_2023' => 'Amélioration continue des mélanges grainiers Continuer la mise en œuvre des essais',
                'created_at' => '2020-04-10 18:53:28',
                'updated_at' => '2020-04-10 18:53:28',
            ),
            27 => 
            array (
                'id' => 28,
                'action_id' => 36,
                'year_2020' => 'Faire l’état des lieux et des tests auprès des producteurs et des consommateurs Etablir un programme de promotion',
                'year_2021' => 'Mener le programme de promotion',
                'year_2022' => 'Mener le programme de promotion',
                'year_2023' => 'À établir lors de la mise en œuvre de l’action',
                'created_at' => '2020-04-10 18:55:24',
                'updated_at' => '2020-04-10 18:55:24',
            ),
            28 => 
            array (
                'id' => 29,
                'action_id' => 37,
            'year_2020' => 'Création d’un groupe de pilotage et mandat attribué 1) sur l’inventaire des variétés et espèces 2) sur l’inventaire des actions',
            'year_2021' => 'En fonction des variétés et espèces recensées et des acteurs identifiés définir des sortes prioritaires, soit pour leur conservation en tant qu’éléments de la diversité génétique soit en vue d’un usage pratique Définir les porteurs de ces usages',
            'year_2022' => 'Promotion des variétés et espèces retenues comme prometteuses, à l’exemple de l’AOP cardon ou de l’artichaut violet',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-10 18:57:27',
            'updated_at' => '2020-04-10 18:57:27',
        ),
        29 => 
        array (
            'id' => 30,
            'action_id' => 38,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:09:40',
            'updated_at' => '2020-04-11 06:09:40',
        ),
        30 => 
        array (
            'id' => 31,
            'action_id' => 39,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:14:31',
            'updated_at' => '2020-04-11 06:14:31',
        ),
        31 => 
        array (
            'id' => 32,
            'action_id' => 40,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:18:14',
            'updated_at' => '2020-04-11 06:18:14',
        ),
        32 => 
        array (
            'id' => 33,
            'action_id' => 41,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:20:28',
            'updated_at' => '2020-04-11 06:20:28',
        ),
        33 => 
        array (
            'id' => 34,
            'action_id' => 42,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:23:03',
            'updated_at' => '2020-04-11 06:23:03',
        ),
        34 => 
        array (
            'id' => 35,
            'action_id' => 43,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:26:04',
            'updated_at' => '2020-04-11 06:26:04',
        ),
        35 => 
        array (
            'id' => 36,
            'action_id' => 44,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:30:30',
            'updated_at' => '2020-04-11 06:30:30',
        ),
        36 => 
        array (
            'id' => 37,
            'action_id' => 45,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:32:21',
            'updated_at' => '2020-04-11 06:32:21',
        ),
        37 => 
        array (
            'id' => 38,
            'action_id' => 46,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 06:34:13',
            'updated_at' => '2020-04-11 06:34:13',
        ),
        38 => 
        array (
            'id' => 39,
            'action_id' => 47,
            'year_2020' => 'Signature des contrats quinquennaux, première année de travaux',
            'year_2021' => 'Deuxième année de travail, auto-évaluation de l’association sur sa durabilité et proposition de mesures.',
            'year_2022' => 'Troisième année de travail, bilan intermédiaire',
            'year_2023' => 'Quatrième année de travail, bilan sur la durabilité de l’association.',
            'created_at' => '2020-04-11 06:40:23',
            'updated_at' => '2020-04-11 06:40:23',
        ),
        39 => 
        array (
            'id' => 40,
            'action_id' => 47,
        'year_2020' => 'Définition annuelle des travaux avec les sociétés (SBG/SMG) et HEPIA',
        'year_2021' => 'Définition annuelle des travaux avec les sociétés (SBG/SMG) et HEPIA',
        'year_2022' => 'Définition annuelle des travaux avec les sociétés (SBG/SMG) et HEPIA',
        'year_2023' => 'Définition annuelle des travaux avec les sociétés (SBG/SMG) et HEPIA',
            'created_at' => '2020-04-11 06:40:23',
            'updated_at' => '2020-04-11 06:40:23',
        ),
        40 => 
        array (
            'id' => 41,
            'action_id' => 48,
            'year_2020' => '1 envoi annuel des données flore dans la base de données Info Flora',
            'year_2021' => '1 envoi annuel des données flore dans la base de données Info Flora',
            'year_2022' => '1 envoi annuel des données flore dans la base de données Info Flora',
            'year_2023' => '1 envoi annuel des données flore dans la base de données Info Flora',
            'created_at' => '2020-04-11 06:44:48',
            'updated_at' => '2020-04-11 06:44:48',
        ),
        41 => 
        array (
            'id' => 42,
            'action_id' => 48,
        'year_2020' => 'SMG : un relevé spécifique sur 2 ans (limite les variations climatiques)',
        'year_2021' => 'SMG : un relevé spécifique sur 2 ans (limite les variations climatiques)',
        'year_2022' => 'SMG : un relevé spécifique sur 2 ans (limite les variations climatiques)',
        'year_2023' => 'SMG : un relevé spécifique sur 2 ans (limite les variations climatiques)',
            'created_at' => '2020-04-11 06:44:48',
            'updated_at' => '2020-04-11 06:44:48',
        ),
        42 => 
        array (
            'id' => 43,
            'action_id' => 48,
            'year_2020' => '1 relevé bryophytes et lichens',
            'year_2021' => '1 relevé bryophytes et lichens',
            'year_2022' => '1 relevé bryophytes et lichens',
            'year_2023' => '1 relevé bryophytes et lichens',
            'created_at' => '2020-04-11 06:44:48',
            'updated_at' => '2020-04-11 06:44:48',
        ),
        43 => 
        array (
            'id' => 44,
            'action_id' => 48,
            'year_2020' => 'Signature du contrat quinquennal avec les CJBG, première année de travaux Première année de suivi',
            'year_2021' => 'Deuxième année de suivi',
            'year_2022' => 'Troisième année de suivi',
            'year_2023' => 'Quatrième année de suivi',
            'created_at' => '2020-04-11 06:44:48',
            'updated_at' => '2020-04-11 06:44:48',
        ),
        44 => 
        array (
            'id' => 45,
            'action_id' => 49,
            'year_2020' => 'Définition de la méthode avec la SOS Calcul de la référence « 2000 »',
            'year_2021' => 'Premiers relevés de terrain',
            'year_2022' => 'Terrain',
            'year_2023' => 'errain et début de l’analyse des résultats, avec comparaison de l’évolution sur 20 ans',
            'created_at' => '2020-04-11 06:47:29',
            'updated_at' => '2020-04-11 06:47:29',
        ),
        45 => 
        array (
            'id' => 46,
            'action_id' => 50,
        'year_2020' => 'Bilan intermédiaire (listes des espèces avec plan d’action, statut de protection, objectifs sur 4 ans). Travail de mise en œuvre',
            'year_2021' => 'Travail de mise en œuvre',
            'year_2022' => 'Travail de mise en œuvre',
            'year_2023' => 'Travail de mise en œuvre, et nouveau bilan intermédiaire',
            'created_at' => '2020-04-11 06:50:56',
            'updated_at' => '2020-04-11 06:50:56',
        ),
        46 => 
        array (
            'id' => 47,
            'action_id' => 51,
        'year_2020' => 'Partage sur les deux méthodes Mise à jour de la méthodologie flore (RPT-CJB)',
            'year_2021' => 'Harmonisation des méthodes',
            'year_2022' => 'Intégration au SITG Communication externe',
            'year_2023' => 'Mise en œuvre',
            'created_at' => '2020-04-11 06:53:20',
            'updated_at' => '2020-04-11 06:53:20',
        ),
        47 => 
        array (
            'id' => 48,
            'action_id' => 52,
            'year_2020' => 'Recherche sur les actions en cours ailleurs, notamment au sein du Monitoring de la biodiversité en Suisse',
            'year_2021' => 'Table ronde sur le sujet réunissant les spécialistes et les organisations actives sur le terrain',
            'year_2022' => 'Définition de protocoles de suivis de la biomasse de la biodiversité genevoise',
            'year_2023' => 'Test des protocoles',
            'created_at' => '2020-04-11 06:56:55',
            'updated_at' => '2020-04-11 06:56:55',
        ),
        48 => 
        array (
            'id' => 49,
            'action_id' => 53,
            'year_2020' => 'Elaboration et constitution des pôles ; poursuite de la mise en œuvre d’actions déjà effectives ou en cours ; recherche de financements',
            'year_2021' => 'Développement des actions à l’ensemble des partenaires',
            'year_2022' => 'Développement des actions à l’ensemble des partenaires',
            'year_2023' => 'Evaluation des objectifs',
            'created_at' => '2020-04-11 07:05:21',
            'updated_at' => '2020-04-11 07:05:21',
        ),
        49 => 
        array (
            'id' => 50,
            'action_id' => 54,
        'year_2020' => 'Publication de normes/ prescriptions. Identification et création de réalisations exemplaires Information/formation des autorités (DT- OU, OAC ; DI-OCGC, OCBA, OCT). Information aux professionnels.',
            'year_2021' => 'Priorisation des secteurs sur lesquels des adaptations sont urgentes. Mise en œuvre.',
            'year_2022' => 'Suite de la mise en œuvre.',
            'year_2023' => 'Bilan de l’effet des prescriptions ; comptabilisation des obstacles et pièges neutralisés.',
            'created_at' => '2020-04-11 07:08:11',
            'updated_at' => '2020-04-11 07:08:11',
        ),
        50 => 
        array (
            'id' => 51,
            'action_id' => 55,
            'year_2020' => 'Identifier les secteurs prioritaires pour la création de plans d’eau, étudier la faisabilité des travaux en collaboration avec les propriétaires, réaliser les travaux.',
            'year_2021' => 'Identifier les secteurs prioritaires pour la création de plans d’eau, étudier la faisabilité des travaux en collaboration avec les propriétaires, réaliser les travaux.',
            'year_2022' => 'Identifier les secteurs prioritaires pour la création de plans d’eau, étudier la faisabilité des travaux en collaboration avec les propriétaires, réaliser les travaux.',
            'year_2023' => 'Identifier les secteurs prioritaires pour la création de plans d’eau, étudier la faisabilité des travaux en collaboration avec les propriétaires, réaliser les travaux.',
            'created_at' => '2020-04-11 07:18:29',
            'updated_at' => '2020-04-11 07:18:29',
        ),
        51 => 
        array (
            'id' => 52,
            'action_id' => 56,
            'year_2020' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'year_2021' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'year_2022' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'year_2023' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'created_at' => '2020-04-11 07:31:16',
            'updated_at' => '2020-04-11 07:31:16',
        ),
        52 => 
        array (
            'id' => 53,
            'action_id' => 57,
            'year_2020' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'year_2021' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'year_2022' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'year_2023' => 'Rencontre annuelle de coordination et subvention annuelle.',
            'created_at' => '2020-04-11 07:44:25',
            'updated_at' => '2020-04-11 07:44:25',
        ),
        53 => 
        array (
            'id' => 54,
            'action_id' => 58,
            'year_2020' => 'Finalisation du site, signature des chartes de partenariat, validation de l’info à mettre en ligne',
            'year_2021' => 'Lancement du site web, test et ajustements',
            'year_2022' => 'Faire vivre le site web en collaboration avec les associations partenaires',
            'year_2023' => 'Faire vivre le site web en collaboration avec les associations partenaires',
            'created_at' => '2020-04-11 07:49:07',
            'updated_at' => '2020-04-11 07:49:07',
        ),
        54 => 
        array (
            'id' => 55,
            'action_id' => 58,
            'year_2020' => 'Finalisation du site, signature des chartes de partenariat, validation de l’info à mettre en ligne',
            'year_2021' => 'Lancement du site web, test et ajustements',
            'year_2022' => 'Faire vivre le site web en collaboration avec les associations partenaires',
            'year_2023' => 'Faire vivre le site web en collaboration avec les associations partenaires',
            'created_at' => '2020-04-11 07:49:09',
            'updated_at' => '2020-04-11 07:49:09',
        ),
        55 => 
        array (
            'id' => 56,
            'action_id' => 59,
            'year_2020' => 'ntégrer dans les usages la terminologie « responsable de programme flore et fonge », que ce soit dans la signature mail, cartes de visites, etc. ou dans les réunions.',
            'year_2021' => 'ntégrer dans les usages la terminologie « responsable de programme flore et fonge », que ce soit dans la signature mail, cartes de visites, etc. ou dans les réunions.',
            'year_2022' => 'ntégrer dans les usages la terminologie « responsable de programme flore et fonge », que ce soit dans la signature mail, cartes de visites, etc. ou dans les réunions.',
            'year_2023' => 'ntégrer dans les usages la terminologie « responsable de programme flore et fonge », que ce soit dans la signature mail, cartes de visites, etc. ou dans les réunions.',
            'created_at' => '2020-04-11 07:51:33',
            'updated_at' => '2020-04-11 07:51:33',
        ),
        56 => 
        array (
            'id' => 57,
            'action_id' => 59,
            'year_2020' => 'Société botanique : 1 publication 2 sorties 2 cours Préparation de la 1ère journée sciences citoyennes Société mycologique : 1 publication 3 sorties',
            'year_2021' => 'Société botanique : 1 publication 2 sorties 2 cours 1 journée sciences citoyennes Société mycologique : 1 publication 3 sorties',
            'year_2022' => 'Société botanique : 1 publication 2 sorties 2 cours 1 journée sciences citoyennes Société mycologique : 1 publication 3 sorties',
            'year_2023' => 'Société botanique : 1 publication 2 sorties 2 cours 1 journée sciences citoyennes Société mycologique : 1 publication 3 sorties',
            'created_at' => '2020-04-11 07:51:33',
            'updated_at' => '2020-04-11 07:51:33',
        ),
        57 => 
        array (
            'id' => 58,
            'action_id' => 60,
            'year_2020' => 'Définition des secteurs à enjeux particuliers et du type de communication Conception des panneaux',
            'year_2021' => 'Mise en œuvre : pose de 30 panneaux',
            'year_2022' => 'Mise en œuvre : pose de 30 panneaux',
            'year_2023' => 'Mise en œuvre : pose de 30 panneaux',
            'created_at' => '2020-04-11 07:54:46',
            'updated_at' => '2020-04-11 07:54:46',
        ),
        58 => 
        array (
            'id' => 59,
            'action_id' => 61,
            'year_2020' => 'Identifier les partenaires potentiels pour la réalisation de l’étude Définition des cas d’hybridation potentielle sur lesquels travailler',
            'year_2021' => 'Proposition de méthode et réalisation des études',
            'year_2022' => 'Communication des résultats et recommandations',
            'year_2023' => 'Mise en œuvre',
            'created_at' => '2020-04-11 08:01:18',
            'updated_at' => '2020-04-11 08:01:18',
        ),
        59 => 
        array (
            'id' => 60,
            'action_id' => 62,
            'year_2020' => 'Préparation du cahier des charges, en vue de la création du poste de référent-e EEE.',
            'year_2021' => 'Création du poste et recrutement d’un référent-e EEE, annoncé à la Confédération.',
            'year_2022' => 'Pilotage de la gestion des EEE par responsable cantonal',
            'year_2023' => 'Pilotage de la gestion des EEE par responsable cantonal',
            'created_at' => '2020-04-11 08:07:17',
            'updated_at' => '2020-04-11 08:07:17',
        ),
        60 => 
        array (
            'id' => 61,
            'action_id' => 62,
            'year_2020' => 'Maintien des coordinations actuelles',
            'year_2021' => 'Répartition formelle des taches entre les services concernés pour les principales espèces problématiques',
        'year_2022' => 'Coordination et soutien aux actions complexes (notamment ambroisie, à terme moustiques tigre, etc.)',
        'year_2023' => 'Coordination bilatérale, soutien aux actions complexes (notamment ambroisie, à terme moustiques tigres, etc.)',
            'created_at' => '2020-04-11 08:07:17',
            'updated_at' => '2020-04-11 08:07:17',
        ),
        61 => 
        array (
            'id' => 62,
            'action_id' => 62,
            'year_2020' => 'Maintien des contacts bilatéraux avec les acteurs transfrontaliers',
            'year_2021' => 'Premières assises transfrontalières pour une mise à jour de l’état des lieux de 2014',
            'year_2022' => 'Définition d’une stratégie et d’un plan d’action commun au niveau trans- frontalier',
            'year_2023' => 'Mise en œuvre des mesures transfrontalières',
            'created_at' => '2020-04-11 08:07:17',
            'updated_at' => '2020-04-11 08:07:17',
        ),
        62 => 
        array (
            'id' => 63,
            'action_id' => 62,
            'year_2020' => 'Mise en œuvre de la stratégie EEE flore',
            'year_2021' => 'Préparation du volet 2023-2033 de la stratégie EEE flore et validation au niveau cantonal',
            'year_2022' => 'Mise en œuvre de la stratégie EEE flore. Validation du volet 2023- 2033 de la stratégie EEE Flore au niveau trans- frontalier',
            'year_2023' => 'Mise en œuvre de la stratégie cantonale EEE flore',
            'created_at' => '2020-04-11 08:07:17',
            'updated_at' => '2020-04-11 08:07:17',
        ),
        63 => 
        array (
            'id' => 64,
            'action_id' => 62,
            'year_2020' => 'Assurer la continuité des actions en cours de luttes contre les EEE faune.',
            'year_2021' => 'Assurer la continuité des actions en cours de luttes contre les EEE faune Préparation d’une stratégie EEE faune',
            'year_2022' => 'Assurer la continuité des actions en cours de luttes contre les EEE faune Validation au niveau can- tonal et au niveau trans- frontalier d’une stratégie EEE faune',
            'year_2023' => 'Mise en œuvre de la stratégie cantonale EEE faune',
            'created_at' => '2020-04-11 08:07:17',
            'updated_at' => '2020-04-11 08:07:17',
        ),
        64 => 
        array (
            'id' => 65,
            'action_id' => 63,
            'year_2020' => 'Poursuite des tests de drone engagés en 2019 et recherche de nouvelles méthodes.',
            'year_2021' => 'Elargissement des méthodes de prévention à tous les secteurs impactés. Bilan intermédiaire.',
            'year_2022' => 'Poursuite de la mise en œuvre, sur la base des expériences acquises. Bilan intermédiaire.',
            'year_2023' => 'Poursuite de la mise en œuvre et bilan final.',
            'created_at' => '2020-04-11 08:12:32',
            'updated_at' => '2020-04-11 08:12:32',
        ),
        65 => 
        array (
            'id' => 66,
            'action_id' => 64,
            'year_2020' => 'Poursuite des monitorings. Définition des objectifs et des méthodes de régulation; mise en œuvre de la régulation des cerfs à Versoix, si nécessaire. Poursuite de la régulation des sangliers à l’échelle du canton et des chevreuils dans le Mandement.',
            'year_2021' => 'Poursuite des monitorings. Poursuite des régulations nécessaires.',
            'year_2022' => 'Idem',
            'year_2023' => 'Idem Bilan de fin de législature',
            'created_at' => '2020-04-11 08:15:50',
            'updated_at' => '2020-04-11 08:15:50',
        ),
        66 => 
        array (
            'id' => 67,
            'action_id' => 65,
            'year_2020' => 'Préparation et création du sondage et réalisation du 1 er sondage Organisation du publiforum',
            'year_2021' => 'Analyse des résultats du sondage – état 0 Réalisation du publiforum',
            'year_2022' => 'Préparation du second sondage Analyse des résultats du publiforum',
            'year_2023' => 'Mise à jour du sondage en fin de législature',
            'created_at' => '2020-04-11 08:18:19',
            'updated_at' => '2020-04-11 08:18:19',
        ),
        67 => 
        array (
            'id' => 68,
            'action_id' => 66,
            'year_2020' => 'Finaliser l’agenda nature, mise en ligne et maintenance',
            'year_2021' => 'Maintenance de l’agenda nature',
            'year_2022' => 'Maintenance de l’agenda nature',
            'year_2023' => 'Maintenance de l’agenda nature',
            'created_at' => '2020-04-11 08:22:32',
            'updated_at' => '2020-04-11 08:22:32',
        ),
        68 => 
        array (
            'id' => 69,
            'action_id' => 66,
            'year_2020' => 'Rencontre et entretiens avec les acteurs Promotion de la plateforme.',
            'year_2021' => 'Rencontre et entretiens avec les acteurs Promotion de la plateforme.',
            'year_2022' => 'Rencontre et entretiens avec les acteurs Promotion de la plateforme.',
            'year_2023' => 'Rencontre et entretiens avec les acteurs Promotion de la plateforme.',
            'created_at' => '2020-04-11 08:22:32',
            'updated_at' => '2020-04-11 08:22:32',
        ),
        69 => 
        array (
            'id' => 70,
            'action_id' => 67,
            'year_2020' => '1. Mai : Emménagement, élaboration du contenu des animations, création du matériel, engagement et formation des animateurs. Septembre : Accueil des premières classes',
            'year_2021' => '1. Accueil des classes durant toute l’année, avec une période plus dense entre avril et juin.',
            'year_2022' => '1. Accueil des classes durant toute l’année, avec une période plus dense entre avril et juin.',
            'year_2023' => '1. Accueil des classes durant toute l’année, avec une période plus dense entre avril et juin.',
            'created_at' => '2020-04-11 08:27:13',
            'updated_at' => '2020-04-11 08:27:13',
        ),
        70 => 
        array (
            'id' => 71,
            'action_id' => 67,
            'year_2020' => '2. Recherche du lieu',
            'year_2021' => '2. Aménagement du lieu et début des animations',
            'year_2022' => '2. Animations et expositions Classes, ateliers et grand public',
            'year_2023' => '2. Animations et expositions Classes, ateliers et grand public',
            'created_at' => '2020-04-11 08:27:14',
            'updated_at' => '2020-04-11 08:27:14',
        ),
        71 => 
        array (
            'id' => 72,
            'action_id' => 68,
            'year_2020' => 'Définition du concept, développement des outils et début de la communication.',
            'year_2021' => 'Evaluation des outils et adaptations éventuelles. Poursuite de la communication',
            'year_2022' => 'Communication',
            'year_2023' => 'Communication',
            'created_at' => '2020-04-11 08:33:53',
            'updated_at' => '2020-04-11 08:33:53',
        ),
        72 => 
        array (
            'id' => 73,
            'action_id' => 69,
            'year_2020' => 'Mise en place, formation de l’équipe',
            'year_2021' => 'Programme de permanences',
            'year_2022' => 'Programme de permanences',
            'year_2023' => 'Programme de permanences Évaluation de la première phase et préparation de la/des suivante/s',
            'created_at' => '2020-04-11 08:36:18',
            'updated_at' => '2020-04-11 08:36:18',
        ),
        73 => 
        array (
            'id' => 74,
            'action_id' => 70,
        'year_2020' => 'Pérenniser la disponibilité du terrain nécessaire aux activités du Parc présentes et futures (voir Annexe2) Développer les programmes pédagogiques et d’intervention assistée par l’animal (IAA) Agrandissement du centre de soins pour l’accueil de la faune sauvage genevoise',
        'year_2021' => 'Idem + Programme de conservation de nouvelles espèces indigènes (par exemple. cistudes, souris des laîches) Programmes de recherche scientifique Agrandissement par étapes des infrastructures du BIOPARC GENEVE pour l’accueil du public (voir plan en Annexe 3)',
            'year_2022' => NULL,
            'year_2023' => NULL,
            'created_at' => '2020-04-11 08:40:25',
            'updated_at' => '2020-04-11 08:40:25',
        ),
        74 => 
        array (
            'id' => 75,
            'action_id' => 71,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 08:43:41',
            'updated_at' => '2020-04-11 08:43:41',
        ),
        75 => 
        array (
            'id' => 76,
            'action_id' => 72,
            'year_2020' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'year_2021' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'year_2022' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'year_2023' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'created_at' => '2020-04-11 08:46:16',
            'updated_at' => '2020-04-11 08:46:16',
        ),
        76 => 
        array (
            'id' => 77,
            'action_id' => 73,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 08:50:39',
            'updated_at' => '2020-04-11 08:50:39',
        ),
        77 => 
        array (
            'id' => 78,
            'action_id' => 74,
            'year_2020' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'year_2021' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'year_2022' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'year_2023' => 'Communication de l’offre aux communes, mise en place et réalisation des sorties',
            'created_at' => '2020-04-11 08:55:19',
            'updated_at' => '2020-04-11 08:55:19',
        ),
        78 => 
        array (
            'id' => 79,
            'action_id' => 75,
            'year_2020' => 'Actions de sensibilisation',
            'year_2021' => 'Actions de sensibilisation',
            'year_2022' => 'Actions de sensibilisation',
            'year_2023' => 'Actions de sensibilisation',
            'created_at' => '2020-04-11 08:58:11',
            'updated_at' => '2020-04-11 08:58:11',
        ),
        79 => 
        array (
            'id' => 80,
            'action_id' => 76,
            'year_2020' => 'Mise à jour et réédition de la brochure “Vivre nos rivières” et élaboration d’autres supports de communication et de sensibilisation',
            'year_2021' => 'Mise à jour et réédition de la brochure “Vivre nos rivières” et élaboration d’autres supports de communication et de sensibilisation',
            'year_2022' => 'Mise à jour et réédition de la brochure “Vivre nos rivières” et élaboration d’autres supports de communication et de sensibilisation',
            'year_2023' => 'Mise à jour et réédition de la brochure “Vivre nos rivières” et élaboration d’autres supports de communication et de sensibilisation',
            'created_at' => '2020-04-11 09:01:35',
            'updated_at' => '2020-04-11 09:01:35',
        ),
        80 => 
        array (
            'id' => 81,
            'action_id' => 77,
            'year_2020' => 'Publication de « Papillons, libellules et sauterelles du canton de Genève »',
            'year_2021' => 'Publication de « Syrphes du canton de Genève »',
            'year_2022' => 'Publication de « Coléoptères remarquables du bassin genevois »',
            'year_2023' => 'Publication de « Atlas des libellules du bassin genevois». Définition des prochains ouvrages',
            'created_at' => '2020-04-11 09:04:09',
            'updated_at' => '2020-04-11 09:04:09',
        ),
        81 => 
        array (
            'id' => 82,
            'action_id' => 78,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 09:07:41',
            'updated_at' => '2020-04-11 09:07:41',
        ),
        82 => 
        array (
            'id' => 83,
            'action_id' => 79,
        'year_2020' => 'En cours (financement assuré pour 150 classes) Prendre la décision si sortie obligatoire pour toutes les classes de 5P',
        'year_2021' => 'En cours (financement assuré pour 150 classes) Faire un appel d’offre pour rechercher partenaires externes pour mener les sorties nature Revoir ou créer un nouveau guide pédagogique pour les enseignant-e-s',
            'year_2022' => '2 x 250 sorties accompagnées pour toutes les classes de 5P En fonction de l’appel d’offre, engager différents partenaires pour assurer les sorties',
            'year_2023' => '2 x 250 sorties accompagnées pour toutes les classes de 5P En fonction de l’appel d’offre, engager différents partenaires pour assurer les sorties',
            'created_at' => '2020-04-11 09:13:52',
            'updated_at' => '2020-04-11 09:13:52',
        ),
        83 => 
        array (
            'id' => 84,
            'action_id' => 80,
        'year_2020' => 'Sorties accompagnées (au minimum 230 sorties) pour les classes dont les enseignants de biologie sont déjà formés aux sorties sur le terrain',
        'year_2021' => 'Sorties accompagnées (au minimum 230 sorties) pour les classes dont les enseignants de biologie doivent être formés aux sorties sur le terrain',
        'year_2022' => 'Sorties accompagnées (au minimum 230 sorties) pour les classes dont les enseignants de biologie doivent être formés aux sorties sur le terrain',
        'year_2023' => 'Sorties accompagnées (au minimum 230 sorties) pour les classes dont les enseignants de biologie doivent être formés aux sorties sur le terrain',
            'created_at' => '2020-04-11 09:16:47',
            'updated_at' => '2020-04-11 09:16:47',
        ),
        84 => 
        array (
            'id' => 85,
            'action_id' => 81,
        'year_2020' => 'Renforcement de la collaboration entre les différents acteurs concernés Organisation d’une conférence en collaboration avec UniGE (HT)',
        'year_2021' => 'Création de ressources numériques pour alimenter les FC + élèves (RTS Découvertes)',
            'year_2022' => 'Création de ressources numériques pour alimenter les FC',
            'year_2023' => 'Création de ressources numériques pour alimenter les FC',
            'created_at' => '2020-04-11 09:21:17',
            'updated_at' => '2020-04-11 09:21:17',
        ),
        85 => 
        array (
            'id' => 86,
            'action_id' => 82,
            'year_2020' => 'Formation continue : Le Léman Formation continue : Agriculture durable et biodiversité Elaboration de nouvelles formations continues et des matériels pédagogiques associés',
            'year_2021' => 'Elaboration de nouvelles formations continues et des matériels pédagogiques associés Coordination et',
            'year_2022' => 'Elaboration de nouvelles formations continues et des matériels pédagogiques associés',
            'year_2023' => 'Elaboration de nouvelles formations continues et des matériels pédagogiques associés',
            'created_at' => '2020-04-11 09:24:21',
            'updated_at' => '2020-04-11 09:24:21',
        ),
        86 => 
        array (
            'id' => 87,
            'action_id' => 83,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 09:26:58',
            'updated_at' => '2020-04-11 09:26:58',
        ),
        87 => 
        array (
            'id' => 88,
            'action_id' => 84,
            'year_2020' => 'Nomination d’un-e coordinateur-trice Biodiversité/EDD Organisation d’une journée d’étude au sein de l’IUFE sur l’EDD pour tous les formateurs-trices Organisation d’une journée d’étude au sein de l’IUFE sur “Biodiversité et EDD” pour les formateurs- trices des didactiques directement concerné- e-s. Listing des contenus et approches qui seront intégrés aux cours/ séminaire/ateliers de didactique mentionnés; Conceptions d’actions à mener sur le terrain pour 2021.',
        'year_2021' => 'Réalisation d’actions sur le terrain. Suivi des réalisations mentionnées (p. 2) : recensement, évaluation en regard des objectifs poursuivis, régulations pour l’année suivante.',
        'year_2022' => 'Réalisation d’actions sur le terrain. Suivi des réalisations mentionnées (p. 2) : recensement, évaluation en regard des objectifs poursuivis, régulations pour l’année suivante.',
        'year_2023' => 'Réalisation d’actions sur le terrain. Suivi des réalisations mentionnées (p. 2) : recensement, évaluation en regard des objectifs poursuivis, régulations pour l’année suivante.',
            'created_at' => '2020-04-11 09:29:57',
            'updated_at' => '2020-04-11 09:29:57',
        ),
        88 => 
        array (
            'id' => 89,
            'action_id' => 85,
            'year_2020' => 'Finalisation et diffusion d’une 1e séquence. Production d’une 2e séquence.',
            'year_2021' => 'Finalisation et diffusion d’une 2e séquence. Production d’une 3e séquence.',
            'year_2022' => 'Finalisation et diffusion d’une 3e séquence. Production d’une 4e séquence.',
            'year_2023' => 'Finalisation et diffusion d’une 4e séquence. Production d’une 4e séquence.',
            'created_at' => '2020-04-11 09:31:55',
            'updated_at' => '2020-04-11 09:31:55',
        ),
        89 => 
        array (
            'id' => 90,
            'action_id' => 86,
            'year_2020' => 'Finalisation et diffusion d’une 1e séquence. Production d’une 2e séquence.',
            'year_2021' => 'Finalisation et diffusion d’une 2e séquence. Production d’une 3e séquence.',
            'year_2022' => 'Finalisation et diffusion d’une 3e séquence. Production d’une 4e séquence.',
            'year_2023' => 'Finalisation et diffusion d’une 4e séquence. Production d’une 4e séquence.',
            'created_at' => '2020-04-11 09:50:55',
            'updated_at' => '2020-04-11 09:50:55',
        ),
        90 => 
        array (
            'id' => 91,
            'action_id' => 87,
            'year_2020' => 'Création d’un groupe de travail',
            'year_2021' => 'Elaboration des ressources',
            'year_2022' => 'Elaboration des ressources',
            'year_2023' => 'Elaboration des ressources',
            'created_at' => '2020-04-11 09:54:10',
            'updated_at' => '2020-04-11 09:54:10',
        ),
        91 => 
        array (
            'id' => 92,
            'action_id' => 88,
        'year_2020' => 'Établir un bilan des actions proposées ces dernières années Mettre en place des sorties lac Établir une liste d’actions possibles autour des établissements par les associations nature Inviter une personne du secondaire II à participer au groupe de travail Sensibilisation nature Diffuser l’Agenda Nature dans les écoles et assurer le financement de certaines sorties (SESAC)',
        'year_2021' => 'Mettre en place un ou deux projets de sensibilisation nature pour les classes en collaboration avec le DT et partenaires Diffuser l’Agenda Nature dans les écoles et assurer le financement de certaines sorties (SESAC)',
        'year_2022' => 'Mettre en place un ou deux projets de sensibilisation nature pour les classes en collaboration avec le DT et partenaires Diffuser l’Agenda Nature dans les écoles et assurer le financement de certaines sorties (SESAC)',
        'year_2023' => 'Mettre en place un ou deux projets de sensibilisation nature pour les classes en collaboration avec le DT et partenaires Diffuser l’Agenda Nature dans les écoles et assurer le financement de certaines sorties (SESAC)',
            'created_at' => '2020-04-11 09:58:01',
            'updated_at' => '2020-04-11 09:58:01',
        ),
        92 => 
        array (
            'id' => 93,
            'action_id' => 89,
        'year_2020' => '• Présentation des associations aux séances de RD • Création d’un onglet biodiversité sur le site Disciplines CO (DIP)',
            'year_2021' => '• Présentation des associations aux séances de RD • Alimenter l’onglet biodiversité sur le site Disciplines CO',
            'year_2022' => '• Présentation des associations aux séances de RD • Alimenter l’onglet biodiversité sur le site Disciplines CO',
            'year_2023' => '• Présentation des associations aux séances de RD • Alimenter l’onglet biodiversité sur le site Disciplines CO',
            'created_at' => '2020-04-11 10:01:07',
            'updated_at' => '2020-04-11 10:01:07',
        ),
        93 => 
        array (
            'id' => 94,
            'action_id' => 90,
        'year_2020' => 'Recenser les actions/ réalisations en cours et les promouvoir au sein des établissements du primaire, au secondaire I et II. Élaborer un concept de formation et lien avec les outils créés (cf. actions 10.3 à 10.11)',
            'year_2021' => 'Évaluer les effets des actions réalisées. Valoriser / diffuser les actions réalisés et les ressources élaborées Exposer le concept d’actions-formation aux établissements : appel à participation.',
            'year_2022' => 'Évaluer les effets des actions soutenues Valoriser / diffuser les actions réalisés et les ressources élaborées',
            'year_2023' => 'Évaluer les effets des actions soutenues Valoriser / diffuser les actions réalisés et les ressources élaborées.',
            'created_at' => '2020-04-11 10:07:40',
            'updated_at' => '2020-04-11 10:07:40',
        ),
        94 => 
        array (
            'id' => 95,
            'action_id' => 90,
            'year_2020' => 'Pour l’EP: Expérimenter un projet d’action et de formation dans une école pilote',
            'year_2021' => 'Pour l’EP: Stabiliser le concept de formation Expérimenter le projet d’action et de formation dans une 2e école pilote Sélectionner les 20 premières écoles retenues pour l’année 2022-2023',
            'year_2022' => 'Pour l’EP: Sélectionner les 20 écoles retenues pour l’année 2023-2024 Mettre en œuvre le projet d’actions- formation dans 20 écoles primaires.',
            'year_2023' => 'Pour l’EP: Sélectionner les 20 écoles retenues pour l’année 2024-2025 Mettre en œuvre le projet d’actions- formation dans 20 écoles primaires',
            'created_at' => '2020-04-11 10:07:40',
            'updated_at' => '2020-04-11 10:07:40',
        ),
        95 => 
        array (
            'id' => 96,
            'action_id' => 90,
        'year_2020' => 'Pour le CO: Sélectionner deux établissements pilotes. Réaliser le projet d’action et de formation dans deux établissements (= groupe 1)',
        'year_2021' => 'Pour le CO: Poursuivre le projet d’action et de formation dans deux établissements (groupe 1) Réaliser le projet d’action et de formation dans ces deux nouveaux établissements (groupe 2)',
        'year_2022' => 'Pour le CO: Poursuivre le projet d’action et de formation dans deux établissements (groupe 2) Réaliser le projet d’action et de formation dans ces deux nouveaux établissements (groupe 3)',
        'year_2023' => 'Pour le CO: Poursuivre le projet d’action et de formation dans deux établissements (groupe 3) Réaliser le projet d’action et de formation dans ces deux nouveaux établissements (groupe 4)',
            'created_at' => '2020-04-11 10:07:40',
            'updated_at' => '2020-04-11 10:07:40',
        ),
        96 => 
        array (
            'id' => 97,
            'action_id' => 90,
            'year_2020' => 'Pour l’ES II: Sélectionner deux établissements pilotes. Réaliser le projet d’action et de formation dans ces deux établissements.',
            'year_2021' => 'Pour l’ES II: Suivi des projets déjà en place. Réaliser le projet d’action et de formation dans au moins 2 nouveaux établissements.',
            'year_2022' => 'Pour l’ES II: Suivi des projets déjà en place. Réaliser le projet d’action et de formation dans au moins 2 nouveaux établissements.',
            'year_2023' => 'Pour l’ES II: Suivi des projets déjà en place. Réaliser le projet d’action et de formation dans au moins 2 nouveaux établissements.',
            'created_at' => '2020-04-11 10:07:40',
            'updated_at' => '2020-04-11 10:07:40',
        ),
        97 => 
        array (
            'id' => 98,
            'action_id' => 91,
            'year_2020' => 'Inventaire des possibilités d’aménagement Enquête Ateliers DIY Bioscope Aménagements supplémentaires à Uni Dufour',
            'year_2021' => 'Campagne d’affichage Programme annuel de sorties nature Lancement de la plateforme d’inventaire participatif et 1er Bioblitz Appel à projets Ateliers DIY Bioscope Aménagements sur 1 ou 2 nouveaux sites',
            'year_2022' => 'Programme annuel de sorties nature Appel à projets Ateliers DIY au Bioscope Aménagements sur 1 ou 2 nouveaux sites Suivi des sites aménagés',
            'year_2023' => 'Ateliers DIY Bioscope Aménagements sur 1 ou 2 nouveaux sites Programme annuel de sorties nature 2e Bioblitz Bilan',
            'created_at' => '2020-04-11 10:10:58',
            'updated_at' => '2020-04-11 10:10:58',
        ),
        98 => 
        array (
            'id' => 99,
            'action_id' => 92,
            'year_2020' => 'Dépôt du dossier',
            'year_2021' => 'Suivi et développement',
            'year_2022' => 'Suivi et développement',
            'year_2023' => 'Suivi et développement',
            'created_at' => '2020-04-11 10:13:56',
            'updated_at' => '2020-04-11 10:13:56',
        ),
        99 => 
        array (
            'id' => 100,
            'action_id' => 93,
        'year_2020' => '• 1 Zoom “métiers verts” (et ODD/biodiversité dans les métiers) / an • 1 manifestation Go apprentissage sur les “métiers verts” / an • Cité des métiers et ODD en 2022 (chaque 3 ans)',
        'year_2021' => '• 1 Zoom “métiers verts” (et ODD/biodiversité dans les métiers) / an • 1 manifestation Go apprentissage sur les “métiers verts” / an • Cité des métiers et ODD en 2022 (chaque 3 ans)',
        'year_2022' => '• 1 Zoom “métiers verts” (et ODD/biodiversité dans les métiers) / an • 1 manifestation Go apprentissage sur les “métiers verts” / an • Cité des métiers et ODD en 2022 (chaque 3 ans)',
        'year_2023' => '• 1 Zoom “métiers verts” (et ODD/biodiversité dans les métiers) / an • 1 manifestation Go apprentissage sur les “métiers verts” / an • Cité des métiers et ODD en 2022 (chaque 3 ans)',
            'created_at' => '2020-04-11 10:16:30',
            'updated_at' => '2020-04-11 10:16:30',
        ),
        100 => 
        array (
            'id' => 101,
            'action_id' => 94,
            'year_2020' => '• Conception d’une formation pour les commissaires d’apprentissage? • Identification de critères pour le contrôle qualité des “cours interentreprises” organisés par les associations professionnelles / lors des examens de fin d’apprentissage / dans les critères d’attribution du Prix de la meilleure entreprise formatrice. • Liste des bonnes pratiques des Ortras, des entreprises formatrices et des centres de formation professionnelle.',
            'year_2021' => '• Conception d’une formation pour les commissaires d’apprentissage? • Identification de critères pour le contrôle qualité des “cours interentreprises” organisés par les associations professionnelles / lors des examens de fin d’apprentissage / dans les critères d’attribution du Prix de la meilleure entreprise formatrice. • Liste des bonnes pratiques des Ortras, des entreprises formatrices et des centres de formation professionnelle.',
            'year_2022' => '• Conception d’une formation pour les commissaires d’apprentissage? • Identification de critères pour le contrôle qualité des “cours interentreprises” organisés par les associations professionnelles / lors des examens de fin d’apprentissage / dans les critères d’attribution du Prix de la meilleure entreprise formatrice. • Liste des bonnes pratiques des Ortras, des entreprises formatrices et des centres de formation professionnelle.',
            'year_2023' => '• Conception d’une formation pour les commissaires d’apprentissage? • Identification de critères pour le contrôle qualité des “cours interentreprises” organisés par les associations professionnelles / lors des examens de fin d’apprentissage / dans les critères d’attribution du Prix de la meilleure entreprise formatrice. • Liste des bonnes pratiques des Ortras, des entreprises formatrices et des centres de formation professionnelle.',
            'created_at' => '2020-04-11 10:20:33',
            'updated_at' => '2020-04-11 10:20:33',
        ),
        101 => 
        array (
            'id' => 102,
            'action_id' => 95,
            'year_2020' => '• promouvoir les fiches “cleantech” au sein des centres de formation professionnelle • diffuser de matériel pédagogique en lien avec les ODD / préservation de l’environnement / Biodiversité adapté aux différentes filières • organiser des “sorties nature” pour les apprenti-e-s au moins une fois dans la formation • promouvoir les bonnes pratiques en matière de préservation de l’environnement / biodiversité auprès des centres de formation professionnelle • vérifier que les aspects EDD/biodiversité sont présents dans les cours interentreprises',
            'year_2021' => '• promouvoir les fiches “cleantech” au sein des centres de formation professionnelle • diffuser de matériel pédagogique en lien avec les ODD / préservation de l’environnement / Biodiversité adapté aux différentes filières • organiser des “sorties nature” pour les apprenti-e-s au moins une fois dans la formation • promouvoir les bonnes pratiques en matière de préservation de l’environnement / biodiversité auprès des centres de formation professionnelle • vérifier que les aspects EDD/biodiversité sont présents dans les cours interentreprises',
            'year_2022' => '• promouvoir les fiches “cleantech” au sein des centres de formation professionnelle • diffuser de matériel pédagogique en lien avec les ODD / préservation de l’environnement / Biodiversité adapté aux différentes filières • organiser des “sorties nature” pour les apprenti-e-s au moins une fois dans la formation • promouvoir les bonnes pratiques en matière de préservation de l’environnement / biodiversité auprès des centres de formation professionnelle • vérifier que les aspects EDD/biodiversité sont présents dans les cours interentreprises',
            'year_2023' => '• promouvoir les fiches “cleantech” au sein des centres de formation professionnelle • diffuser de matériel pédagogique en lien avec les ODD / préservation de l’environnement / Biodiversité adapté aux différentes filières • organiser des “sorties nature” pour les apprenti-e-s au moins une fois dans la formation • promouvoir les bonnes pratiques en matière de préservation de l’environnement / biodiversité auprès des centres de formation professionnelle • vérifier que les aspects EDD/biodiversité sont présents dans les cours interentreprises',
            'created_at' => '2020-04-11 10:22:13',
            'updated_at' => '2020-04-11 10:22:13',
        ),
        102 => 
        array (
            'id' => 103,
            'action_id' => 96,
            'year_2020' => '2020: élaboration du plan d’études 2021: mise en œuvre du plan d’études',
            'year_2021' => '2020: élaboration du plan d’études 2021: mise en œuvre du plan d’études',
            'year_2022' => '2020: élaboration du plan d’études 2021: mise en œuvre du plan d’études',
            'year_2023' => '2020: élaboration du plan d’études 2021: mise en œuvre du plan d’études',
            'created_at' => '2020-04-11 10:25:51',
            'updated_at' => '2020-04-11 10:25:51',
        ),
        103 => 
        array (
            'id' => 104,
            'action_id' => 97,
            'year_2020' => 'Définition d’un groupe de travail, identification des besoins et attentes, définition des thèmes et la forme des cours. Développement du contenu des cours.',
            'year_2021' => 'Développement du contenu des cours et ouverture des inscriptions.',
            'year_2022' => 'Dispense des premières formations.',
            'year_2023' => 'Poursuite des formations.',
            'created_at' => '2020-04-11 10:29:01',
            'updated_at' => '2020-04-11 10:29:01',
        ),
        104 => 
        array (
            'id' => 105,
            'action_id' => 98,
            'year_2020' => 'Mise en place de la formation',
            'year_2021' => 'Formation effective',
            'year_2022' => 'Formation effective',
            'year_2023' => 'Formation effective et bilan',
            'created_at' => '2020-04-11 10:31:41',
            'updated_at' => '2020-04-11 10:31:41',
        ),
        105 => 
        array (
            'id' => 106,
            'action_id' => 99,
            'year_2020' => 'Janvier à juin / septembre à décembre Prises de contacts avec les enseignant-es Animations avec les classes Fiches de satisfaction auprès des enseignant-es',
            'year_2021' => 'Janvier à juin / septembre à décembre Prises de contacts avec les enseignant-es Animations avec les classes Fiches de satisfaction auprès des enseignant-es',
            'year_2022' => 'Janvier à juin / septembre à décembre Prises de contacts avec les enseignant-es Animations avec les classes Fiches de satisfaction auprès des enseignant-es',
            'year_2023' => 'Janvier à juin / septembre à décembre Prises de contacts avec les enseignant-es Animations avec les classes Fiches de satisfaction auprès des enseignant-es',
            'created_at' => '2020-04-11 10:33:03',
            'updated_at' => '2020-04-11 10:33:03',
        ),
        106 => 
        array (
            'id' => 107,
            'action_id' => 100,
            'year_2020' => 'Actions/Etapes 3 et 4',
            'year_2021' => 'Actions/Etapes 4',
            'year_2022' => 'Actions/Etapes 5',
            'year_2023' => 'Actions/Etapes 5 et 6',
            'created_at' => '2020-04-11 10:36:34',
            'updated_at' => '2020-04-11 10:36:34',
        ),
        107 => 
        array (
            'id' => 108,
            'action_id' => 101,
            'year_2020' => 'Actions/Etapes 1 et 2',
            'year_2021' => 'Actions/Etapes 3',
            'year_2022' => 'Actions/Etapes 4 et 5',
            'year_2023' => 'Actions/Etapes 4 et 5',
            'created_at' => '2020-04-11 10:40:35',
            'updated_at' => '2020-04-11 10:40:35',
        ),
        108 => 
        array (
            'id' => 109,
            'action_id' => 102,
            'year_2020' => 'Actions/Etapes 1 à 4',
            'year_2021' => 'Actions/Etapes 1 à 3',
            'year_2022' => 'Actions/Etapes 1 à 2',
            'year_2023' => 'Actions/Etapes 1 à 2',
            'created_at' => '2020-04-11 10:45:38',
            'updated_at' => '2020-04-11 10:45:38',
        ),
        109 => 
        array (
            'id' => 110,
            'action_id' => 103,
            'year_2020' => 'Actions/Etapes 1',
            'year_2021' => 'Actions/Etapes 1',
            'year_2022' => 'Actions/Etapes 2',
            'year_2023' => 'Actions/Etapes 2',
            'created_at' => '2020-04-11 10:49:04',
            'updated_at' => '2020-04-11 10:49:04',
        ),
        110 => 
        array (
            'id' => 111,
            'action_id' => 104,
            'year_2020' => 'Actions/Etapes 1 et 2',
            'year_2021' => 'Actions/Etapes 1 et 2',
            'year_2022' => 'Actions/Etapes 1 et 2',
            'year_2023' => 'Actions/Etapes 1 et 2',
            'created_at' => '2020-04-11 10:52:48',
            'updated_at' => '2020-04-11 10:52:48',
        ),
        111 => 
        array (
            'id' => 112,
            'action_id' => 105,
            'year_2020' => 'Actions/Etapes 1',
            'year_2021' => 'Actions/Etapes 1',
            'year_2022' => 'Actions/Etapes 1',
            'year_2023' => 'Actions/Etapes 1',
            'created_at' => '2020-04-11 10:56:02',
            'updated_at' => '2020-04-11 10:56:02',
        ),
        112 => 
        array (
            'id' => 113,
            'action_id' => 106,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 10:59:39',
            'updated_at' => '2020-04-11 10:59:39',
        ),
        113 => 
        array (
            'id' => 114,
            'action_id' => 107,
        'year_2020' => 'Identifier les relais biodiversité dans les communes et organiser une 1ère rencontre Etat/communes pour faire le suivi des actions, fixer les objectifs et identifier les besoins (lien avec atelier thématique du 23 mai 2019)',
            'year_2021' => 'Faciliter la mise en œuvre des actions par la mise à disposition d’outils et d’informations pratiques',
            'year_2022' => 'Poursuivre l’accompagnement à la mise en œuvre des actions communales',
            'year_2023' => 'Poursuivre l’accompagnement à la mise en œuvre des actions communales',
            'created_at' => '2020-04-11 11:05:31',
            'updated_at' => '2020-04-11 11:05:31',
        ),
        114 => 
        array (
            'id' => 115,
            'action_id' => 108,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 11:07:24',
            'updated_at' => '2020-04-11 11:07:24',
        ),
        115 => 
        array (
            'id' => 116,
            'action_id' => 109,
        'year_2020' => 'Inventaire du dispositif légal (bases légales, procédures de planification, instances de décision, etc.)',
            'year_2021' => 'Proposition d’évolution du dispositif pour intégrer les critères en lien avec la biodiversité',
            'year_2022' => 'Validation et application du dispositif et représentation de la biodiversité dans les instances appropriées',
            'year_2023' => 'Bilan et adaptation',
            'created_at' => '2020-04-11 11:09:25',
            'updated_at' => '2020-04-11 11:09:25',
        ),
        116 => 
        array (
            'id' => 117,
            'action_id' => 110,
            'year_2020' => 'Mandat lancé',
            'year_2021' => 'Résultats de l’étude et mise en œuvre',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 11:13:20',
            'updated_at' => '2020-04-11 11:13:20',
        ),
        117 => 
        array (
            'id' => 118,
            'action_id' => 111,
            'year_2020' => 'Evaluation des alternatives possibles et projets pilotes',
            'year_2021' => 'Mise en œuvre à l’échelle du territoire',
            'year_2022' => 'Mise en œuvre à l’échelle du territoire',
            'year_2023' => 'Bilan et perspectives',
            'created_at' => '2020-04-11 11:16:16',
            'updated_at' => '2020-04-11 11:16:16',
        ),
        118 => 
        array (
            'id' => 119,
            'action_id' => 112,
        'year_2020' => 'Evaluation de l’existant, benchmark des alternatives possibles en Suisse et ailleurs, proposition de solutions (dispositif existant et nouveau)',
            'year_2021' => 'Evaluation des solutions, sur des projets pilotes et retour d’expériences',
            'year_2022' => 'Validation et accompagnement au déploiement de ces mesures',
            'year_2023' => 'Bilan et perspectives',
            'created_at' => '2020-04-11 11:19:56',
            'updated_at' => '2020-04-11 11:19:56',
        ),
        119 => 
        array (
            'id' => 120,
            'action_id' => 113,
            'year_2020' => 'Identification des projets de solidarité internationale soutenus par le Canton, et pistes de mise en œuvre dans le cadre d’actions en faveur de la biodiversité',
            'year_2021' => 'Identification d’objectifs et d’actions et préparation à la mise en œuvre',
            'year_2022' => 'Accompagnement à la mise en œuvre et/ou suivi',
            'year_2023' => 'Accompagnement à la mise en œuvre et/ou suivi et bilan intermédiaire',
            'created_at' => '2020-04-11 11:22:02',
            'updated_at' => '2020-04-11 11:22:02',
        ),
        120 => 
        array (
            'id' => 121,
            'action_id' => 114,
            'year_2020' => 'Valider la nomination d’un référent biodiversité au sein de l’OCAN et entreprendre les démarches nécessaires',
            'year_2021' => 'Prise en main du poste et attributions des tâches',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 11:24:54',
            'updated_at' => '2020-04-11 11:24:54',
        ),
        121 => 
        array (
            'id' => 122,
            'action_id' => 115,
            'year_2020' => 'Création du groupe de travail, inventaire des données existantes et des référentiels, définition des objectifs et choix des indicateurs',
            'year_2021' => 'Poursuite de la démarche, élaboration des premiers indicateurs et présentation/validation aux acteurs concernés',
            'year_2022' => 'Poursuite démarche',
            'year_2023' => 'Etablissement des indicateurs',
            'created_at' => '2020-04-11 11:26:27',
            'updated_at' => '2020-04-11 11:26:27',
        ),
        122 => 
        array (
            'id' => 123,
            'action_id' => 116,
            'year_2020' => 'Analyse des causes comportementales en lien avec les actions',
            'year_2021' => 'Idem + sélection des outils ad hoc',
            'year_2022' => 'Analyse des comportements en lien avec les actions',
            'year_2023' => 'Organisation des ateliers en fonction des catégories de comportements identifiés',
            'created_at' => '2020-04-11 11:28:41',
            'updated_at' => '2020-04-11 11:28:41',
        ),
        123 => 
        array (
            'id' => 124,
            'action_id' => 117,
            'year_2020' => 'À établir lors de la mise en œuvre de l’action',
            'year_2021' => 'À établir lors de la mise en œuvre de l’action',
            'year_2022' => 'À établir lors de la mise en œuvre de l’action',
            'year_2023' => 'À établir lors de la mise en œuvre de l’action',
            'created_at' => '2020-04-11 11:30:45',
            'updated_at' => '2020-04-11 11:30:45',
        ),
        124 => 
        array (
            'id' => 125,
            'action_id' => 118,
            'year_2020' => 'Mener l’étude de faisabilité pour la création de l’Agence',
            'year_2021' => 'Evaluer les résultats et définir la suite à donner',
            'year_2022' => NULL,
            'year_2023' => NULL,
            'created_at' => '2020-04-11 11:32:14',
            'updated_at' => '2020-04-11 11:32:14',
        ),
    ));
        
        
    }
}