<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'entreprise_id' => NULL,
                'name' => 'A. Blaser',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:52:34',
                'updated_at' => '2020-03-30 18:52:34',
            ),
            1 => 
            array (
                'id' => 2,
                'entreprise_id' => NULL,
                'name' => 'V. Jaggi',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:53:08',
                'updated_at' => '2020-03-30 18:53:08',
            ),
            2 => 
            array (
                'id' => 3,
                'entreprise_id' => NULL,
                'name' => 'V. Demule',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:53:13',
                'updated_at' => '2020-03-30 18:53:13',
            ),
            3 => 
            array (
                'id' => 4,
                'entreprise_id' => NULL,
                'name' => 'A. Rauss',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:53:29',
                'updated_at' => '2020-03-30 18:53:29',
            ),
            4 => 
            array (
                'id' => 5,
                'entreprise_id' => NULL,
                'name' => 'Y. Bourguignon',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:53:41',
                'updated_at' => '2020-03-30 18:53:41',
            ),
            5 => 
            array (
                'id' => 6,
                'entreprise_id' => NULL,
                'name' => 'P. Fouvy',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:53:46',
                'updated_at' => '2020-03-30 18:53:46',
            ),
            6 => 
            array (
                'id' => 7,
                'entreprise_id' => NULL,
                'name' => 'B. Favre',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:53:56',
                'updated_at' => '2020-03-30 18:53:56',
            ),
            7 => 
            array (
                'id' => 8,
                'entreprise_id' => NULL,
                'name' => 'F. Bachmann',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:56:27',
                'updated_at' => '2020-03-30 18:56:27',
            ),
            8 => 
            array (
                'id' => 9,
                'entreprise_id' => NULL,
                'name' => 'N. à Porta',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:56:33',
                'updated_at' => '2020-03-30 18:56:33',
            ),
            9 => 
            array (
                'id' => 10,
                'entreprise_id' => 2,
                'name' => 'D. Ansuini',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:56:59',
                'updated_at' => '2020-03-30 18:56:59',
            ),
            10 => 
            array (
                'id' => 11,
                'entreprise_id' => 3,
                'name' => 'A. Dufour',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:57:48',
                'updated_at' => '2020-03-30 18:57:48',
            ),
            11 => 
            array (
                'id' => 12,
                'entreprise_id' => 7,
                'name' => 'E. Lecomte',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:58:35',
                'updated_at' => '2020-03-30 18:58:35',
            ),
            12 => 
            array (
                'id' => 13,
                'entreprise_id' => 2,
                'name' => 'D. Jaquet',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 18:59:38',
                'updated_at' => '2020-03-30 18:59:38',
            ),
            13 => 
            array (
                'id' => 14,
                'entreprise_id' => 1,
                'name' => 'M. Jaggi',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 19:00:07',
                'updated_at' => '2020-03-30 19:00:07',
            ),
            14 => 
            array (
                'id' => 15,
                'entreprise_id' => 2,
                'name' => 'PJ. Copin',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 19:00:25',
                'updated_at' => '2020-03-30 19:00:25',
            ),
            15 => 
            array (
                'id' => 16,
                'entreprise_id' => 2,
                'name' => 'D. Ceresetti',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-30 19:00:51',
                'updated_at' => '2020-03-30 19:00:51',
            ),
            16 => 
            array (
                'id' => 17,
                'entreprise_id' => 2,
                'name' => 'A. Cordonier',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:05:51',
                'updated_at' => '2020-03-31 07:05:51',
            ),
            17 => 
            array (
                'id' => 18,
                'entreprise_id' => 2,
                'name' => 'M. Coster',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:06:13',
                'updated_at' => '2020-03-31 07:06:13',
            ),
            18 => 
            array (
                'id' => 19,
                'entreprise_id' => 2,
                'name' => 'J. Schlup',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:09:05',
                'updated_at' => '2020-03-31 07:09:05',
            ),
            19 => 
            array (
                'id' => 20,
                'entreprise_id' => NULL,
                'name' => 'M. Bessat',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:09:23',
                'updated_at' => '2020-03-31 07:09:23',
            ),
            20 => 
            array (
                'id' => 21,
                'entreprise_id' => NULL,
                'name' => 'JM. Sermet',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:09:44',
                'updated_at' => '2020-03-31 07:09:44',
            ),
            21 => 
            array (
                'id' => 22,
                'entreprise_id' => 1,
                'name' => 'AL. Cantiniaux',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:10:02',
                'updated_at' => '2020-03-31 07:10:02',
            ),
            22 => 
            array (
                'id' => 23,
                'entreprise_id' => NULL,
                'name' => 'V. Venizelos',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:10:36',
                'updated_at' => '2020-03-31 07:10:36',
            ),
            23 => 
            array (
                'id' => 24,
                'entreprise_id' => NULL,
                'name' => 'G. Dandliker',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:10:56',
                'updated_at' => '2020-03-31 07:10:56',
            ),
            24 => 
            array (
                'id' => 25,
                'entreprise_id' => NULL,
                'name' => 'E. Favre',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:11:01',
                'updated_at' => '2020-03-31 07:11:01',
            ),
            25 => 
            array (
                'id' => 26,
                'entreprise_id' => 15,
                'name' => 'C. Pochelon',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:11:26',
                'updated_at' => '2020-03-31 07:11:26',
            ),
            26 => 
            array (
                'id' => 27,
                'entreprise_id' => 23,
                'name' => 'Mickaël Blanc',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:11:54',
                'updated_at' => '2020-03-31 07:11:54',
            ),
            27 => 
            array (
                'id' => 28,
                'entreprise_id' => NULL,
                'name' => 'J. Thiébaud',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:12:05',
                'updated_at' => '2020-03-31 07:12:05',
            ),
            28 => 
            array (
                'id' => 29,
                'entreprise_id' => NULL,
                'name' => 'J. Gyger',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:12:18',
                'updated_at' => '2020-03-31 07:12:18',
            ),
            29 => 
            array (
                'id' => 30,
                'entreprise_id' => NULL,
                'name' => 'C. Rochet',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:13:26',
                'updated_at' => '2020-03-31 07:13:26',
            ),
            30 => 
            array (
                'id' => 31,
                'entreprise_id' => 7,
                'name' => 'JM. Mitterer',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:13:44',
                'updated_at' => '2020-03-31 07:13:44',
            ),
            31 => 
            array (
                'id' => 32,
                'entreprise_id' => NULL,
                'name' => 'A. Maraia',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:14:27',
                'updated_at' => '2020-03-31 07:14:27',
            ),
            32 => 
            array (
                'id' => 33,
                'entreprise_id' => NULL,
                'name' => 'D. Rappaz',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:14:40',
                'updated_at' => '2020-03-31 07:14:40',
            ),
            33 => 
            array (
                'id' => 34,
                'entreprise_id' => NULL,
                'name' => 'S. Mader',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:14:46',
                'updated_at' => '2020-03-31 07:14:46',
            ),
            34 => 
            array (
                'id' => 35,
                'entreprise_id' => NULL,
                'name' => 'Olivia Spahni',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:15:37',
                'updated_at' => '2020-03-31 07:15:37',
            ),
            35 => 
            array (
                'id' => 36,
                'entreprise_id' => 30,
                'name' => 'Dr vétérinaire Tobias BLAHA',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:16:48',
                'updated_at' => '2020-03-31 07:16:48',
            ),
            36 => 
            array (
                'id' => 37,
                'entreprise_id' => 30,
                'name' => 'Dr Anne-Sophie DEVILLE',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:17:06',
                'updated_at' => '2020-03-31 07:17:06',
            ),
            37 => 
            array (
                'id' => 38,
                'entreprise_id' => 32,
                'name' => 'C. Yvon',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:17:44',
                'updated_at' => '2020-03-31 07:17:44',
            ),
            38 => 
            array (
                'id' => 39,
                'entreprise_id' => 23,
                'name' => 'M. Blanc',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:18:26',
                'updated_at' => '2020-03-31 07:18:26',
            ),
            39 => 
            array (
                'id' => 40,
                'entreprise_id' => 38,
                'name' => 'Gilles Mulhauser',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:19:42',
                'updated_at' => '2020-03-31 07:19:42',
            ),
            40 => 
            array (
                'id' => 41,
                'entreprise_id' => NULL,
                'name' => 'Natacha à Porta',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:20:21',
                'updated_at' => '2020-03-31 07:20:21',
            ),
            41 => 
            array (
                'id' => 42,
                'entreprise_id' => NULL,
                'name' => 'Céline Rochet',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:21:11',
                'updated_at' => '2020-03-31 07:21:11',
            ),
            42 => 
            array (
                'id' => 43,
                'entreprise_id' => NULL,
                'name' => 'Gottlieb Dandliker',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:21:17',
                'updated_at' => '2020-03-31 07:21:17',
            ),
            43 => 
            array (
                'id' => 44,
                'entreprise_id' => 39,
                'name' => 'Mathieu Bondallaz',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:22:45',
                'updated_at' => '2020-03-31 07:22:45',
            ),
            44 => 
            array (
                'id' => 45,
                'entreprise_id' => NULL,
                'name' => 'Isabelle Vuillemin',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:22:59',
                'updated_at' => '2020-03-31 07:22:59',
            ),
            45 => 
            array (
                'id' => 46,
                'entreprise_id' => 41,
                'name' => 'Patricia Naegeli',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:26:49',
                'updated_at' => '2020-03-31 07:26:49',
            ),
            46 => 
            array (
                'id' => 47,
                'entreprise_id' => 42,
                'name' => 'Claudine Dayer Fournet',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:27:09',
                'updated_at' => '2020-03-31 07:27:09',
            ),
            47 => 
            array (
                'id' => 48,
                'entreprise_id' => 43,
                'name' => 'Julien Perrot',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:28:17',
                'updated_at' => '2020-03-31 07:28:17',
            ),
            48 => 
            array (
                'id' => 49,
                'entreprise_id' => 32,
                'name' => 'Candice Yvon Mathieu Petite',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:29:11',
                'updated_at' => '2020-03-31 07:29:11',
            ),
            49 => 
            array (
                'id' => 50,
                'entreprise_id' => 44,
                'name' => 'jean Lebedeff',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:29:56',
                'updated_at' => '2020-03-31 07:29:56',
            ),
            50 => 
            array (
                'id' => 51,
                'entreprise_id' => 44,
                'name' => 'Marc Miéville',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:30:15',
                'updated_at' => '2020-03-31 07:30:15',
            ),
            51 => 
            array (
                'id' => 52,
                'entreprise_id' => 45,
                'name' => 'Erwin Fischer',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:30:57',
                'updated_at' => '2020-03-31 07:30:57',
            ),
            52 => 
            array (
                'id' => 53,
                'entreprise_id' => 45,
                'name' => 'JP Cattin',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:31:26',
                'updated_at' => '2020-03-31 07:31:26',
            ),
            53 => 
            array (
                'id' => 54,
                'entreprise_id' => 41,
                'name' => 'David De Vito',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:32:02',
                'updated_at' => '2020-03-31 07:32:02',
            ),
            54 => 
            array (
                'id' => 55,
                'entreprise_id' => 37,
                'name' => 'Isaline Probst',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:35:06',
                'updated_at' => '2020-03-31 07:35:06',
            ),
            55 => 
            array (
                'id' => 56,
                'entreprise_id' => 46,
                'name' => 'HEPIA',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:35:55',
                'updated_at' => '2020-03-31 07:35:55',
            ),
            56 => 
            array (
                'id' => 57,
                'entreprise_id' => NULL,
                'name' => 'M. Yves Hausser',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:36:00',
                'updated_at' => '2020-03-31 07:36:00',
            ),
            57 => 
            array (
                'id' => 58,
                'entreprise_id' => 34,
                'name' => 'Suzanne Mader',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:36:14',
                'updated_at' => '2020-03-31 07:36:14',
            ),
            58 => 
            array (
                'id' => 59,
                'entreprise_id' => NULL,
                'name' => 'J. Massy',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:36:21',
                'updated_at' => '2020-03-31 07:36:21',
            ),
            59 => 
            array (
                'id' => 60,
                'entreprise_id' => NULL,
                'name' => 'N. Wyler',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:36:37',
                'updated_at' => '2020-03-31 07:36:37',
            ),
            60 => 
            array (
                'id' => 61,
                'entreprise_id' => 1,
                'name' => 'B. Von Arx',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:37:00',
                'updated_at' => '2020-03-31 07:37:00',
            ),
            61 => 
            array (
                'id' => 62,
                'entreprise_id' => 47,
                'name' => 'A. Hervo',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:37:28',
                'updated_at' => '2020-03-31 07:37:28',
            ),
            62 => 
            array (
                'id' => 63,
                'entreprise_id' => NULL,
                'name' => 'Olivier Desrichard',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:38:19',
                'updated_at' => '2020-03-31 07:38:19',
            ),
            63 => 
            array (
                'id' => 64,
                'entreprise_id' => 32,
                'name' => 'Lisa Moussaoui',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:38:35',
                'updated_at' => '2020-03-31 07:38:35',
            ),
            64 => 
            array (
                'id' => 65,
                'entreprise_id' => NULL,
                'name' => 'R. Longet',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-31 07:38:51',
                'updated_at' => '2020-03-31 07:38:51',
            ),
        ));
        
        
    }
}